version: "3.8"

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports: 6379:6379
  api:
    build: ./apps/api
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  engine:
    build: ./apps/engine
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
